### ISSUE TITLE
No support for multiple i2c addresses - Update i2c library to 0.1.4

### ISSUE THREAD

**Issue by riczorn** [kaosat-dev/adafruit-i2c-pwm-driver#1]
Hi, 

please upgrade the package to include i2c library 0.1.4. It supports multiple pwm chips on the i2c.

I am currently using adafruit-i2c-pwm-driver successfully (after update to i2c 0.1.4) to drive a raspberry shield with two PCA9865 chips by pridopia.co.uk (I know that the adafruit only has one).

Also you might want to include packages using an "x" for the patch i.e. 
"i2c" = "0.1.x"

Thank you

**Comment by kaosat-dev** [comment]
Hi @riczorn , thanks for the info, I will modify & update the code & dependencies accordingly this weekend !
Thanks!

**Comment by EMCP** [comment]
might want to go to `v0.2.3` now instead.. lot of updates

**Comment by kaosat-dev** [comment]
@riczorn this library was now updated and uses the latest I2c lib (0.2.3) , can you please try the new version ? Not that there were some minor api changes (x = new PwmDriver() is now x = makePwmDriver() , etc, please check the updated readme for more info)

**Comment by kaosat-dev** [comment]
No news , I guess it works ? Closing. If it does not work I'll re open
