### ISSUE TITLE
I can't install as a node package on windows

### ISSUE THREAD

**Issue by Soulskater** [kaosat-dev/adafruit-i2c-pwm-driver#2]
I'm trying to develop node js servo control on windows in webstorm ide, but i always get an error during npm install.
Could you help me why is this happens?

**Comment by EMCP** [comment]
you should likely paste the errors

**Comment by kaosat-dev** [comment]
@Soulskater this library just got a lot of updates, could you please try again with the updated version? If it still fails, please post the actual error message(s) ?

**Comment by Soulskater** [comment]
Yes i got it work thanks!

**Comment by kaosat-dev** [comment]
cool closing this then.
