### ISSUE TITLE
Readme example incorrect

### ISSUE THREAD

**Issue by tobiasmuecksch** [kaosat-dev/adafruit-i2c-pwm-driver#9]
In the readme this package is required like this:

```
const makePwmDriver = require('adafruit-i2c-pwm')
```

This doesn't work for me. Instead this worked:

```
const makePwmDriver = require('adafruit-i2c-pwm-driver')
```

As far as I can tell the readme needs to be updated there. Am I right?

**Comment by kaosat-dev** [comment]
Indeed you are, thanks! :) Fixed & updated both here and on npm.
